### ISSUE TITLE
Section 2.2.3 (Intro) Suggested Edits

### ISSUE THREAD

**Issue by rajesh06** [OpenActTexts/Loss-Data-Analytics#5]
First paragraph, first sentence: Suggest that "Statistics" not be capitalized

More Generally: Suggest that "Binomial" and  Negative Binomial" not be capitalized

First paragraph, last sentence: add "various" before "reasons"

Second bullet: suggest removing "convex hulls" as this is not a commonly used term for a set of distributions. It's also not commonly used in actuarial work and I suggest that it makes the sentence harder to read without adding significant understanding.

**Comment by larryleihua** [comment]
Thx, agree with Statistics | Binomial Negative | Binomial | various kinda stuff. I will revise these pretty soon. Regarding "convex hulls", I agree with u, but I am not quite sure about what the original contributor wanted to say; I leave it as is, and will try to contact the original contributor to clarify it.

By the way, your feedback is appreciated, and actually you know what you could just edit it whenever you find something and pull a request so that it becomes much more effective.

Thx! 
-L.

**Comment by rajesh06** [comment]
Thanks - I have had debates about the pull request v issues. My understanding is that pull requests are for break / fix items. My understanding is that issues are better for suggested corrections.

**Comment by larryleihua** [comment]
This issue has been partially solved. Please someone respond to the "convex hulls" issue.
